### ISSUE TITLE
PointCloud2 enhancements

### ISSUE THREAD

**Issue by athackst** [osrf/rvizweb#29]
Below is an image of a rgbd topic:
* RGB values not shown
* Point size not configurable
![Screenshot from 2019-03-18 16-36-39](https://user-images.githubusercontent.com/6098197/54570572-3ede6980-499c-11e9-8175-49dd0a9ed1af.png)

**Comment by jubeira** [comment]
@athackst understood!
Just one quick question: have you tried modifying the `size` parameter below the topic? That one should be working, and the color is indeed missing.

Same pointcloud with different point sizes:
![image](https://user-images.githubusercontent.com/2480899/54619629-b0bdbe00-4a43-11e9-8379-4beb752fec34.png)

![image](https://user-images.githubusercontent.com/2480899/54619661-bd421680-4a43-11e9-8d79-7e27ba579b2f.png)

**Comment by athackst** [comment]
size works as expected (thanks!)

Would still be great to have color/rgb values

**Comment by jubeira** [comment]
@athackst I've taken a look at this, and it should be possible to display the pointcloud with the current `ros3djs` according to the RGB values if they are contained in the message.

Just to double check: is this your case? The pointcloud should have a field dedicated to the color in it's `field` member, e.g.:

```
fields: 
  - 
    name: "x"
    offset: 0
    datatype: 7
    count: 1
  - 
    name: "y"
    offset: 4
    datatype: 7
    count: 1
  - 
    name: "z"
    offset: 8
    datatype: 7
    count: 1
  - 
    name: "rgb"
    offset: 12
    datatype: 7
    count: 1
```

The reason I'm asking is because `rviz` has other options to add colors to a pointcloud, so I'd like to be in the same page.
For the record, here's a [reference](https://github.com/RobotWebTools/ros3djs/blob/develop/src/sensors/Points.js#L61-L84) to the code that parses the color from the message.
