### ISSUE TITLE
Point cloud delayed

### ISSUE THREAD

**Issue by athackst** [osrf/rvizweb#9]
I'm running TF and points (from a velodyne) and we're seeing a really long lag between the display and true data

**Comment by mvollrath** [comment]
PointCloud2 performance has been bad because it is sending base64-encoded data in a JSON string, which is large over the wire, slow to decode, and expensive to convert back to binary data.  It is greatly improved as of [this ros3djs commit on develop branch](https://github.com/RobotWebTools/ros3djs/commit/e3fb0ad8d971d666357c7b49fbeea9e87c06d463) which switches to the new [CBOR binary encoding](https://github.com/RobotWebTools/rosbridge_suite/issues/367).

We will also need to use roslibjs of at least [this commit on develop branch](https://github.com/RobotWebTools/roslibjs/commit/94676d1fef402e1174822c0c35d52de253497db4) for binary decoding.

We will need to run it against rosbridge_suite of at least 0.10.1 for binary encoding, which is released to melodic and set to be included in [the next kinetic sync](https://discourse.ros.org/t/preparing-for-kinetic-sync-2019-01-03/7300).

I will work out a PR to switch to the new client code once the kinetic sync is released.

**Comment by jubeira** [comment]
Hi @mvollrath,

I've been trying to use the latest `ros3djs#develop` together with the latest `rosbridge_suite` to check if this solved the issue, but I couldn't get the basic `pointcloud2` example to work properly using a simulated Turtlebot / PR2. Here's the description of the issue: https://github.com/RobotWebTools/ros3djs/issues/243 (note that I checked the pointcloud and I see no NaNs in the message).

Am I missing something obvious? Do I need to do anything specific to use `CBOR` besides using the latest `rosbridge_suite` from source?

**Comment by mvollrath** [comment]
You need to use roslibjs from develop branch, things will probably be broken until they release it.

**Comment by mvollrath** [comment]
I think that turtlebot cloud you're trying to use has a different point format, ros3djs seems like it only supports one.  Also it's epic huge.

**Comment by jubeira** [comment]
> I think that turtlebot cloud you're trying to use has a different point format, ros3djs seems like it only supports one. Also it's epic huge.

Note that I could see the pointcloud with `ros3djs@master` (with a huge delay, and streaming only a few secs to prevent overflowing my PC's RAM), so that's why I thought it was not a format issue in this case. Did that change in `develop` branch as well?
And yes, the amount of data is really big, but it's also a pretty common example to work on.

I'll give `roslibjs@develop` branch a shot as you propose.

**Comment by mvollrath** [comment]
There's a different code path for decoding binary vs. base64 PointCloud2 data, for whatever reason.  That's probably it works on master but not over CBOR.

The PointCloud2 data in the turtlebot thing is malformed.  Either the fields are mislabeled or 50% of the data is unused bloat.

**Comment by jubeira** [comment]
> The PointCloud2 data in the turtlebot thing is malformed. Either the fields are mislabeled or 50% of the data is unused bloat.

Yes, when I print the data on the console I see a large amount of `0`s everywhere. 
Today I tried the latest `ros3djs` examples and `rosbridge_suite` with a different pointcloud source ([tango ros streamer](https://github.com/intermodalics/tango_ros)) and it worked fine.

The pointcloud coming from Turtlebot Gazebo **(not ok)** has the following metadata:
```
juan@Sullust:~$ rostopic echo /camera/depth/points 
header: 
  seq: 0
  stamp: 
    secs: 15
    nsecs: 430000000
  frame_id: "camera_depth_optical_frame"
height: 480
width: 640
fields: 
  - 
    name: "x"
    offset: 0
    datatype: 7
    count: 1
  - 
    name: "y"
    offset: 4
    datatype: 7
    count: 1
  - 
    name: "z"
    offset: 8
    datatype: 7
    count: 1
  - 
    name: "rgb"
    offset: 16
    datatype: 7
    count: 1
is_bigendian: False
point_step: 32
row_step: 20480
```

while the one coming from the Tango device **(ok)** has the following:
```
juan@Sullust:~$ rostopic echo /tango/point_cloud 
header: 
  seq: 0
  stamp: 
    secs: 1546889935
    nsecs: 391690969
  frame_id: "camera_depth"
height: 1
width: 32987
fields: 
  - 
    name: "x"
    offset: 0
    datatype: 7
    count: 1
  - 
    name: "y"
    offset: 4
    datatype: 7
    count: 1
  - 
    name: "z"
    offset: 8
    datatype: 7
    count: 1
  - 
    name: "c"
    offset: 12
    datatype: 7
    count: 1
is_bigendian: False
point_step: 16
row_step: 527792
```

Then, the one coming from Gazebo has twice the point step. `datatype` 7 is `FLOAT32`, so yes, considering the offsets and the point steps there are 4 'bloat' bytes at offset 12 and 12 'bloat; bytes at offset 20. Basically half of the bytes in the message are useless.
Other than that `row_step` vs `width` and `height` ratios are different, but I'm not sure if that's a problem or not in this case; both messages seem to be consistent at least.

I will try viewing the pointcloud in `rvizweb` as well to see what happens using `ros3djs@develop`; if the issue with the pointcloud coming from Gazebo a format problem we can tackle that afterwards.
